# Script for populating the database. You can run it as:
#
#     mix run priv/repo/seeds.exs
#
# Inside the script, you can read and write to any of your
# repositories directly:
#
#     Adellis.Repo.insert!(%Adellis.SomeSchema{})
#
# We recommend using the bang functions (`insert!`, `update!`
# and so on) as they will fail if something goes wrong.

alias Adellis.Repo
alias Adellis.Catalog.Product

products = [
  %Product{
    nsn: "5365000012306",
    nsn_formatted: "5365-00-0012306",
    name: "SPACER, SLEEVE",
    item_name_code: 13207,
    type_of_item_identification_code: "K"
  },
  %Product{
    nsn: "6685000041672",
    nsn_formatted: "6685-00-0041672",
    name: "INDICATOR, HUMIDITY, CARD",
    item_name_code: 13474,
    type_of_item_identification_code: "1"
  },
  %Product{
    nsn: "5365000012999",
    nsn_formatted: "5365-00-0012999",
    name: "SPACER, FAKE",
    item_name_code: 13207,
    type_of_item_identification_code: "K"
  },
  %Product{
    nsn: "6685000041990",
    nsn_formatted: "6685-00-0041990",
    name: "INDICATOR, HUMIDITY, CARD, FAKE",
    item_name_code: 13474,
    type_of_item_identification_code: "1"
  },
  %Product{
    nsn: "5365000012991",
    nsn_formatted: "5365-00-0012991",
    name: "SPACER, BOLT, FAKE",
    item_name_code: 13207,
    type_of_item_identification_code: "K"
  },
  %Product{
    nsn: "6685000041993",
    nsn_formatted: "6685-00-0041993",
    name: "COMPUTER, FAKE",
    item_name_code: 13474,
    type_of_item_identification_code: "1"
  },
  %Product{
    nsn: "5365000012996",
    nsn_formatted: "5365-00-0012996",
    name: "SPACESHIP, FAKE",
    item_name_code: 13207,
    type_of_item_identification_code: "K"
  },
  %Product{
    nsn: "6685000041888",
    nsn_formatted: "6685-00-0041888",
    name: "CARD, MEMORY, FAKE",
    item_name_code: 13474,
    type_of_item_identification_code: "1"
  }
]

Enum.map(products, fn product -> Repo.insert!(product) end)

alias Adellis.Catalog.Demilitarization
demils = [ 
%Demilitarization{code: "A", description: "Items subject to the Export Administration Regulations (EAR) in parts 773-74 of Title 15, Code of Federal Regulations (CFR) (CCLI or EAR99) and determined by the DoD to present a low risk when released out of DoD control. No DEMIL, MUT or end use certificate is required. May require an export license from DOC. "},
%Demilitarization{code: "B", description: "USML Items - Multilation (MUT) to the point of scrap required worldwide."},
%Demilitarization{code: "C", description: "USML or CCL Military Items- DEMIL required. Remove  or demilitarize installed key points(s) items as DEMIL code D"},
%Demilitarization{code: "D", description: "USML or CCL Military Items- DEMIL required. Destroy item and components to prevent restoration or repair to a usable condition."},
%Demilitarization{code: "E", description: "DOD DEMIL Program Office  reserves this code for its exclusive - use only. DEMIL instructions must be furnished by the DoD DEMIL Program Office."},
%Demilitarization{code: "F", description: "USML or CCL Military Items- DEMIL required.  Item  managers, equipment specialists, or product specialist must furnish special DEMIL instructions."},
%Demilitarization{code: "G", description: "USML or CCL Military Items- DEMIL required- ammunition and explosives (AE). This code applies to both unclassified and classified AE items."},
%Demilitarization{code: "P", description: "USML Items- DEMIL required. Security Classified Items."},
%Demilitarization{code: "Q", description: "Commerce Control List Items (CCLI) - MUT to the point of scrap required outside the United States. Inside the United States, MUT is required when the DEMIL  Intergrity Code. (IC)  3 and MUT is not required when the DEMIL IS is 6.."}
]


Enum.map(demils, fn demil -> Repo.insert!(demil) end)

alias Adellis.Catalog.FederalSupplyClassification
fscs = [ 
%FederalSupplyClassification{id: 1210, name: "Fire Control Directors"},
%FederalSupplyClassification{id: 1220, name: "Fire Control Computing Sights and Devices"},
%FederalSupplyClassification{id: 1230, name: "Fire Control Systems, Complete"},
%FederalSupplyClassification{id: 1240, name: "Optical Sighting and Ranging Equipment"},
%FederalSupplyClassification{id: 1250, name: "Fire Control Stabilizing Mechanisms"},
%FederalSupplyClassification{id: 1260, name: "Fire Control Designating and Indicating Equipment"},
%FederalSupplyClassification{id: 1265, name: "Fire Control Transmitting and Receiving Equipment, except Airborne"},
%FederalSupplyClassification{id: 1270, name: "Aircraft Gunnery Fire Control Components"},
%FederalSupplyClassification{id: 1280, name: "Aircraft Bombing Fire Control Components"},
%FederalSupplyClassification{id: 1285, name: "Fire Control Radar Equipment, except Airborne"},
%FederalSupplyClassification{id: 1287, name: "Fire Control Sonar Equipment"},
%FederalSupplyClassification{id: 1290, name: "Miscellaneous Fire Control Equipment"},
%FederalSupplyClassification{id: 1510, name: "Aircraft, Fixed Wing"},
%FederalSupplyClassification{id: 1520, name: "Aircraft, Rotary Wing"},
%FederalSupplyClassification{id: 1540, name: "Gliders"},
%FederalSupplyClassification{id: 1550, name: "Unmanned Aircraft"},
%FederalSupplyClassification{id: 1560, name: "Airframe Structural Components"},
%FederalSupplyClassification{id: 1610, name: "Aircraft Propellers and Components"},
%FederalSupplyClassification{id: 1620, name: "Aircraft Landing Gear Components"},
%FederalSupplyClassification{id: 1630, name: "Aircraft Wheel and Brake Systems"},
%FederalSupplyClassification{id: 1640, name: "Aircraft Control Cable Products"},
%FederalSupplyClassification{id: 1650, name: "Aircraft Hydraulic, Vacuum, and De-icing System Components"},
%FederalSupplyClassification{id: 1660, name: "Aircraft Air Conditioning, Heating, and Pressurizing Equipment"},
%FederalSupplyClassification{id: 1670, name: "Parachutes; Aerial Pick Up, Delivery, Recovery Systems; and Cargo Tie Down Equipment"},
%FederalSupplyClassification{id: 1680, name: "Miscellaneous Aircraft Accessories and Components"},
%FederalSupplyClassification{id: 1710, name: "Aircraft Landing Equipment"},
%FederalSupplyClassification{id: 1720, name: "Aircraft Launching Equipment"},
%FederalSupplyClassification{id: 1730, name: "Aircraft Ground Servicing Equipment"},
%FederalSupplyClassification{id: 1740, name: "Airfield Specialized Trucks and Trailers"},
%FederalSupplyClassification{id: 1810, name: "Space Vehicles"},
%FederalSupplyClassification{id: 1820, name: "Space Vehicle Components"},
%FederalSupplyClassification{id: 1905, name: "Combat Ships and Landing Vessels"},
%FederalSupplyClassification{id: 1910, name: "Transport Vessels, Passenger and Troop"},
%FederalSupplyClassification{id: 1915, name: "Cargo and Tanker Vessels"},
%FederalSupplyClassification{id: 1920, name: "Fishing Vessels"},
%FederalSupplyClassification{id: 1925, name: "Special Service Vessels"},
%FederalSupplyClassification{id: 1930, name: "Barges and Lighters, Cargo"},
%FederalSupplyClassification{id: 1935, name: "Barges and Lighters, Special Purpose"},
%FederalSupplyClassification{id: 1940, name: "Small Craft"},
%FederalSupplyClassification{id: 1945, name: "Pontoons and Floating Docks"},
%FederalSupplyClassification{id: 1950, name: "Floating Drydocks"},
%FederalSupplyClassification{id: 1955, name: "Dredges"},
%FederalSupplyClassification{id: 1990, name: "Miscellaneous Vessels"},
%FederalSupplyClassification{id: 2010, name: "Ship and Boat Propulsion Components"},
%FederalSupplyClassification{id: 2020, name: "Rigging and Rigging Gear"},
%FederalSupplyClassification{id: 2230, name: "Right-of-Way Construction and Maintenance Equipment, Railroad"},
%FederalSupplyClassification{id: 2240, name: "Locomotive and Rail Car Accessories and Components"},
%FederalSupplyClassification{id: 2250, name: "Track Material, Railroad"},
%FederalSupplyClassification{id: 2305, name: "Ground Effect Vehicles"},
%FederalSupplyClassification{id: 2310, name: "Passenger Motor Vehicles"},
%FederalSupplyClassification{id: 2320, name: "Trucks and Truck Tractors, Wheeled"},
%FederalSupplyClassification{id: 2330, name: "Trailers"},
%FederalSupplyClassification{id: 2340, name: "Motorcycles, Motor Scooters, and Bicycles"},
%FederalSupplyClassification{id: 2350, name: "Combat, Assault, and Tactical Vehicles, Tracked"},
%FederalSupplyClassification{id: 2355, name: "Combat, Assault, and Tactical Vehicles, Wheeled"},
%FederalSupplyClassification{id: 2410, name: "Tractor, Full Tracked, Low Speed"},
%FederalSupplyClassification{id: 2420, name: "Tractors, Wheeled"},
%FederalSupplyClassification{id: 2430, name: "Tractors, Full Tracked, High Speed"},
%FederalSupplyClassification{id: 2510, name: "Vehicular Cab, Body, and Frame Structural Components"},
%FederalSupplyClassification{id: 2520, name: "Vehicular Power Transmission Components"},
%FederalSupplyClassification{id: 2530, name: "Vehicular Brake, Steering, Axle, Wheel, and Track Components"},
%FederalSupplyClassification{id: 2540, name: "Vehicular Furniture and Accessories"},
%FederalSupplyClassification{id: 2541, name: "Weapons Systems Specific Vehicular Accessories"},
%FederalSupplyClassification{id: 2590, name: "Miscellaneous Vehicular Components"},
%FederalSupplyClassification{id: 2610, name: "Tires and Tubes, Pneumatic, Except Aircraft"},
%FederalSupplyClassification{id: 2620, name: "Tires and Tubes, Pneumatic, Aircraft"},
%FederalSupplyClassification{id: 2630, name: "Tires, Solid and Cushion"},
%FederalSupplyClassification{id: 2640, name: "Tire Rebuilding and Tire and Tube Repair Materials"},
%FederalSupplyClassification{id: 2805, name: "Gasoline Reciprocating Engines, Except Aircraft; and Components"},
%FederalSupplyClassification{id: 2810, name: "Gasoline Reciprocating Engines, Aircraft Prime Mover; and Components"},
%FederalSupplyClassification{id: 2815, name: "Diesel Engines and Components"},
%FederalSupplyClassification{id: 2820, name: "Steam Engines, Reciprocating; and Components"},
%FederalSupplyClassification{id: 2825, name: "Steam Turbines and Components"},
%FederalSupplyClassification{id: 2830, name: "Water Turbines and Water Wheels; and Components"},
%FederalSupplyClassification{id: 2835, name: "Gas Turbines and Jet Engines; Non-Aircraft Prime Mover, Aircraft Non-Prime Mover, and Components"},
%FederalSupplyClassification{id: 2840, name: "Gas Turbines and Jet Engines, Aircraft, Prime Moving; and Components"},
%FederalSupplyClassification{id: 2845, name: "Rocket Engines and Components"},
%FederalSupplyClassification{id: 2850, name: "Gasoline Rotary Engines and Components"},
%FederalSupplyClassification{id: 2895, name: "Miscellaneous Engines and Components"},
%FederalSupplyClassification{id: 2910, name: "Engine Fuel System Components, Nonaircraft"},
%FederalSupplyClassification{id: 2915, name: "Engine Fuel System Components, Aircraft and Missile Prime Movers"},
%FederalSupplyClassification{id: 2920, name: "Engine Electrical System Components, Nonaircraft"},
%FederalSupplyClassification{id: 2925, name: "Engine Electrical System Components, Aircraft Prime Moving"},
%FederalSupplyClassification{id: 2930, name: "Engine Cooling System Components, Nonaircraft"},
%FederalSupplyClassification{id: 2935, name: "Engine System Cooling Components, Aircraft Prime Moving"},
%FederalSupplyClassification{id: 2940, name: "Engine Air and Oil Filters, Strainers, and Cleaners, Nonaircraft"},
%FederalSupplyClassification{id: 2945, name: "Engine Air and Oil Filters, Cleaners, Aircraft Prime Moving"},
%FederalSupplyClassification{id: 2950, name: "Turbosupercharger and Components"},
%FederalSupplyClassification{id: 2990, name: "Miscellaneous Engine Accessories, Nonaircraft"},
%FederalSupplyClassification{id: 2995, name: "Miscellaneous Engine Accessories, Aircraft"},
%FederalSupplyClassification{id: 3010, name: "Torque Converters and Speed Changers"},
%FederalSupplyClassification{id: 3020, name: "Gears, Pulleys, Sprockets, and Transmission Chain"},
%FederalSupplyClassification{id: 3030, name: "Belting, Drive Belts, Fan Belts, and Accessories"},
%FederalSupplyClassification{id: 3040, name: "Miscellaneous Power Transmission Equipment"},
%FederalSupplyClassification{id: 3110, name: "Bearings, Antifriction, Unmounted"},
%FederalSupplyClassification{id: 3120, name: "Bearings, Plain, Unmounted"},
%FederalSupplyClassification{id: 3130, name: "Bearings, Mounted"},
%FederalSupplyClassification{id: 3210, name: "Sawmill and Planing Mill Machinery"},
%FederalSupplyClassification{id: 3220, name: "Woodworking Machines"},
%FederalSupplyClassification{id: 3230, name: "Tools and Attachments for Woodworking Machinery"},
%FederalSupplyClassification{id: 3405, name: "Saws and Filing Machines"},
%FederalSupplyClassification{id: 3408, name: "Machining Centers and Way-Type Machines"},
%FederalSupplyClassification{id: 3410, name: "Electrical and Ultrasonic Erosion Machines"},
%FederalSupplyClassification{id: 3411, name: "Boring Machines"},
%FederalSupplyClassification{id: 3412, name: "Broaching Machines"},
%FederalSupplyClassification{id: 3413, name: "Drilling and Tapping Machines"},
%FederalSupplyClassification{id: 3414, name: "Gear Cutting and Finishing Machines"},
%FederalSupplyClassification{id: 3415, name: "Grinding Machines"},
%FederalSupplyClassification{id: 3416, name: "Lathes"},
%FederalSupplyClassification{id: 3417, name: "Milling Machines"},
%FederalSupplyClassification{id: 3418, name: "Planers and Shapers"},
%FederalSupplyClassification{id: 3419, name: "Miscellaneous Machine Tools"},
%FederalSupplyClassification{id: 3424, name: "Metal Heat Treating and Non-Thermal Treating Equipment"},
%FederalSupplyClassification{id: 3426, name: "Metal Finishing Equipment"},
%FederalSupplyClassification{id: 3431, name: "Electric Arc Welding Equipment"},
%FederalSupplyClassification{id: 3432, name: "Electric Resistance Welding Equipment"},
%FederalSupplyClassification{id: 3433, name: "Gas Welding, Heat Cutting, and Metalizing Equipment"},
%FederalSupplyClassification{id: 3436, name: "Welding Positioners and Manipulators"},
%FederalSupplyClassification{id: 3438, name: "Miscellaneous Welding Equipment"},
%FederalSupplyClassification{id: 3439, name: "Miscellaneous Welding, Soldering, and Brazing Supplies and Accessories"},
%FederalSupplyClassification{id: 3441, name: "Bending and Forming Machines"},
%FederalSupplyClassification{id: 3442, name: "Hydraulic and Pneumatic Presses, Power Driven"},
%FederalSupplyClassification{id: 3443, name: "Mechanical Presses, Power Driven"},
%FederalSupplyClassification{id: 3444, name: "Manual Presses"},
%FederalSupplyClassification{id: 3445, name: "Punching and Shearing Machines"},
%FederalSupplyClassification{id: 3446, name: "Forging Machinery and Hammers"},
%FederalSupplyClassification{id: 3447, name: "Wire and Metal Ribbon Forming Machines"},
%FederalSupplyClassification{id: 3448, name: "Riveting Machines"},
%FederalSupplyClassification{id: 3449, name: "Miscellaneous Secondary Metal Forming and Cutting Machines"},
%FederalSupplyClassification{id: 3450, name: "Machine Tools, Portable"},
%FederalSupplyClassification{id: 3455, name: "Cutting Tools for Machine Tools"},
%FederalSupplyClassification{id: 3456, name: "Cutting and Forming Tools for Secondary Metalworking Machinery"},
%FederalSupplyClassification{id: 3460, name: "Machine Tool accessories"},
%FederalSupplyClassification{id: 3461, name: "Accessories for Secondary Metalworking Machinery"},
%FederalSupplyClassification{id: 3465, name: "Production Jigs, Fixtures, and Templates"},
%FederalSupplyClassification{id: 3470, name: "Machine Shop Sets, Kits, and Outfits"},
%FederalSupplyClassification{id: 3510, name: "Laundry and Dry Cleaning Equipment"},
%FederalSupplyClassification{id: 3520, name: "Shoe Repairing Equipment"},
%FederalSupplyClassification{id: 3530, name: "Industrial Sewing Machines and Mobile Textile Repair Shops"},
%FederalSupplyClassification{id: 3540, name: "Wrapping and Packaging Machinery"},
%FederalSupplyClassification{id: 3590, name: "Miscellaneous Service and Trade Equipment"},
%FederalSupplyClassification{id: 3605, name: "Food Products Machinery and Equipment"},
%FederalSupplyClassification{id: 3610, name: "Printing, Duplicating, and Bookbinding Equipment"},
%FederalSupplyClassification{id: 3611, name: "Industrial Marking Machines"},
%FederalSupplyClassification{id: 3615, name: "Pulp and Paper Industries Machinery"},
%FederalSupplyClassification{id: 3620, name: "Rubber and Plastics Working Machinery"},
%FederalSupplyClassification{id: 3625, name: "Textile Industries Machinery"},
%FederalSupplyClassification{id: 3630, name: "Clay and Concrete Products Industries Machinery"},
%FederalSupplyClassification{id: 3635, name: "Crystal and Glass Industries Machinery"},
%FederalSupplyClassification{id: 3650, name: "Chemical and Pharmaceutical Products Manufacturing Machinery"},
%FederalSupplyClassification{id: 3655, name: "Gas Generating and Dispensing Systems, Fixed or Mobile"},
%FederalSupplyClassification{id: 3660, name: "Industrial Size Reduction Machinery"},
%FederalSupplyClassification{id: 3670, name: "Specialized Semiconductor, Microcircuit, and Printed Circuit Board Manufacturing Machinery"},
%FederalSupplyClassification{id: 3680, name: "Foundry Machinery, Related Equipment and Supplies"},
%FederalSupplyClassification{id: 3685, name: "Specialized Metal Container Manufacturing Machinery and Related Equipment"},
%FederalSupplyClassification{id: 3693, name: "Industrial Assembly Machines"},
%FederalSupplyClassification{id: 3694, name: "Clean Work Stations, Controlled Environment, and Related Equipment"},
%FederalSupplyClassification{id: 3695, name: "Miscellaneous Special Industry Machinery"},
%FederalSupplyClassification{id: 3710, name: "Soil Preparation Equipment"},
%FederalSupplyClassification{id: 3805, name: "Earth Moving and Excavating Equipment"},
%FederalSupplyClassification{id: 3810, name: "Cranes and Crane-Shovels"},
%FederalSupplyClassification{id: 3815, name: "Crane and Crane-Shovel Attachments"},
%FederalSupplyClassification{id: 3820, name: "Mining, Rock Drilling, Earth Boring, and Related Equipment"},
%FederalSupplyClassification{id: 3825, name: "Road Clearing, Cleaning, and Marking Equipment"},
%FederalSupplyClassification{id: 3830, name: "Truck and Tractor Attachments"},
%FederalSupplyClassification{id: 3835, name: "Petroleum Production and Distribution Equipment"},
%FederalSupplyClassification{id: 3895, name: "Miscellaneous Construction Equipment"},
%FederalSupplyClassification{id: 3910, name: "Conveyors"},
%FederalSupplyClassification{id: 3920, name: "Material Handling Equipment, Nonself-Propelled"},
%FederalSupplyClassification{id: 3930, name: "Warehouse Trucks and Tractors, Self-Propelled"},
%FederalSupplyClassification{id: 3940, name: "Blocks, Tackle, Rigging, and Slings"},
%FederalSupplyClassification{id: 3950, name: "Winches, Hoists, Cranes, and Derricks"},
%FederalSupplyClassification{id: 3960, name: "Freight Elevators"},
%FederalSupplyClassification{id: 3990, name: "Miscellaneous Materials Handling Equipment"},
%FederalSupplyClassification{id: 4010, name: "Chain and Wire Rope"},
%FederalSupplyClassification{id: 4020, name: "Fiber Rope, Cordage, and Twine"},
%FederalSupplyClassification{id: 4030, name: "Fittings for Rope, Cable, and Chain"},
%FederalSupplyClassification{id: 4110, name: "Refrigeration Equipment"},
%FederalSupplyClassification{id: 4120, name: "Air Conditioning Equipment"},
%FederalSupplyClassification{id: 4130, name: "Refrigeration and Air Conditioning Components"},
%FederalSupplyClassification{id: 4140, name: "Fans, Air Circulators, and Blower Equipment"},
%FederalSupplyClassification{id: 4210, name: "Fire Fighting Equipment"},
%FederalSupplyClassification{id: 4220, name: "Marine Lifesaving and Diving Equipment"},
%FederalSupplyClassification{id: 4230, name: "Decontaminating and Impregnating Equipment"},
%FederalSupplyClassification{id: 4235, name: "Hazardous Material Spill Containment and Clean-up Equipment and Material"},
%FederalSupplyClassification{id: 4240, name: "Safety and Rescue Equipment"},
%FederalSupplyClassification{id: 4250, name: "Recycling and Reclamation Equipment"},
%FederalSupplyClassification{id: 4310, name: "Compressors and Vacuum Pumps"},
%FederalSupplyClassification{id: 4320, name: "Power and Hand Pumps"},
%FederalSupplyClassification{id: 4330, name: "Centrifugals, Separators, and Pressure and Vacuum Filters"},
%FederalSupplyClassification{id: 4410, name: "Industrial Boilers"},
%FederalSupplyClassification{id: 4420, name: "Heat Exchangers and Steam Condensers"},
%FederalSupplyClassification{id: 4430, name: "Industrial Furnaces, Kilns, Lehrs, and Ovens"},
%FederalSupplyClassification{id: 4440, name: "Driers, Dehydrators, and Anhydrators"},
%FederalSupplyClassification{id: 4460, name: "Air Purification Equipment"},
%FederalSupplyClassification{id: 4470, name: "Nuclear Reactors"},
%FederalSupplyClassification{id: 4510, name: "Plumbing Fixtures and Accessories"},
%FederalSupplyClassification{id: 4520, name: "Space and Water Heating Equipment"},
%FederalSupplyClassification{id: 4530, name: "Fuel Burning Equipment Units"},
%FederalSupplyClassification{id: 4540, name: "Waste Disposal Equipment"},
%FederalSupplyClassification{id: 4610, name: "Water Purification Equipment"},
%FederalSupplyClassification{id: 4620, name: "Water Distillation Equipment, Marine and Industrial"},
%FederalSupplyClassification{id: 4630, name: "Sewage Treatment Equipment"},
%FederalSupplyClassification{id: 4710, name: "PIPE, TUBE AND RIGID TUBING"},
%FederalSupplyClassification{id: 4720, name: "Hose and Flexible Tubing"},
%FederalSupplyClassification{id: 4730, name: "Hose, Pipe, Tube, Lubrication, and Railing Fittings"},
%FederalSupplyClassification{id: 4810, name: "Valves, Powered"},
%FederalSupplyClassification{id: 4820, name: "Valves, Nonpowered"},
%FederalSupplyClassification{id: 4910, name: "Motor Vehicle Maintenance and Repair Shop Specialized Equipment"},
%FederalSupplyClassification{id: 4920, name: "Aircraft Maintenance and Repair Shop Specialized Equipment"},
%FederalSupplyClassification{id: 4921, name: "Torpedo Maintenance, Repair, and Checkout Specialized Equipment"},
%FederalSupplyClassification{id: 4925, name: "Ammunition Maintenance, Repair, and Checkout Specialized Equipment"},
%FederalSupplyClassification{id: 4927, name: "Rocket Maintenance, Repair and Checkout Specialized Equipment"},
%FederalSupplyClassification{id: 4930, name: "Lubrication and Fuel Dispensing Equipment"},
%FederalSupplyClassification{id: 4931, name: "Fire Control Maintenance and Repair Shop Specialized Equipment"},
%FederalSupplyClassification{id: 4933, name: "Weapons Maintenance and Repair Shop Specialized Equipment"},
%FederalSupplyClassification{id: 4935, name: "Guided Missile Maintenance, Repair, and Checkout Specialized Equipment"},
%FederalSupplyClassification{id: 4940, name: "Miscellaneous Maintenance and Repair Shop Specialized Equipment"},
%FederalSupplyClassification{id: 5110, name: "Hand Tools, Edged, Nonpowered"},
%FederalSupplyClassification{id: 5120, name: "Hand Tools, Nonedged, Nonpowered"},
%FederalSupplyClassification{id: 5130, name: "Hand Tools, Power Driven"},
%FederalSupplyClassification{id: 5133, name: "Drill Bits, Counterbores, and Countersinks: Hand and Machine"},
%FederalSupplyClassification{id: 5136, name: "Taps, Dies, and Collets; Hand and Machine"},
%FederalSupplyClassification{id: 5140, name: "Tool and Hardware Boxes"},
%FederalSupplyClassification{id: 5180, name: "Sets, Kits, and Outfits of Hand Tools"},
%FederalSupplyClassification{id: 5210, name: "Measuring Tools, Craftsmen's"},
%FederalSupplyClassification{id: 5220, name: "Inspection Gages and Precision Layout Tools"},
%FederalSupplyClassification{id: 5280, name: "Sets, Kits, and Outfits of Measuring Tools"},
%FederalSupplyClassification{id: 5305, name: "Screws"},
%FederalSupplyClassification{id: 5306, name: "Bolts"},
%FederalSupplyClassification{id: 5307, name: "Studs"},
%FederalSupplyClassification{id: 5310, name: "Nuts and Washers"},
%FederalSupplyClassification{id: 5315, name: "Nails, Machine Keys, and Pins"},
%FederalSupplyClassification{id: 5320, name: "Rivets"},
%FederalSupplyClassification{id: 5325, name: "Fastening Devices"},
%FederalSupplyClassification{id: 5330, name: "Packing and Gasket Materials"},
%FederalSupplyClassification{id: 5331, name: "O-Ring"},
%FederalSupplyClassification{id: 5335, name: "Metal Screening"},
%FederalSupplyClassification{id: 5340, name: "Hardware, Commercial"},
%FederalSupplyClassification{id: 5342, name: "Hardware, Weapon System"},
%FederalSupplyClassification{id: 5345, name: "Disks and Stones, Abrasive"},
%FederalSupplyClassification{id: 5350, name: "Abrasive Materials"},
%FederalSupplyClassification{id: 5355, name: "Knobs and Pointers"},
%FederalSupplyClassification{id: 5360, name: "Coil, Flat, Leaf, and Wire Springs"},
%FederalSupplyClassification{id: 5365, name: "Bushings, Rings, Shims, and Spacers"},
%FederalSupplyClassification{id: 5410, name: "Prefabricated and Portable Buildings"},
%FederalSupplyClassification{id: 5411, name: "Rigid Wall Shelters"},
%FederalSupplyClassification{id: 5420, name: "Bridges, Fixed and Floating"},
%FederalSupplyClassification{id: 5430, name: "Storage Tanks"},
%FederalSupplyClassification{id: 5440, name: "Scaffolding Equipment and Concrete Forms"},
%FederalSupplyClassification{id: 5450, name: "Miscellaneous Prefabricated Structures"},
%FederalSupplyClassification{id: 5510, name: "Lumber and Related Basic Wood Materials"},
%FederalSupplyClassification{id: 5610, name: "Mineral Construction Materials, Bulk"},
%FederalSupplyClassification{id: 5640, name: "Wallboard, Building Paper, and Thermal Insulation Materials"},
%FederalSupplyClassification{id: 5660, name: "Fencing, Fences, Gates and Components"},
%FederalSupplyClassification{id: 5670, name: "Building Components, Prefabricated"},
%FederalSupplyClassification{id: 5675, name: "Nonwood Construction Lumber and Related Materials"},
%FederalSupplyClassification{id: 5680, name: "Miscellaneous Construction Materials"},
%FederalSupplyClassification{id: 5805, name: "Telephone and Telegraph Equipment"},
%FederalSupplyClassification{id: 5810, name: "Communications Security Equipment and Components"},
%FederalSupplyClassification{id: 5811, name: "Other Cryptologic Equipment and Components"},
%FederalSupplyClassification{id: 5815, name: "Teletype and Facsimile Equipment"},
%FederalSupplyClassification{id: 5820, name: "Radio and Television Communication Equipment, Except Airborne"},
%FederalSupplyClassification{id: 5821, name: "Radio and Television Communication Equipment, Airborne"},
%FederalSupplyClassification{id: 5825, name: "Radio Navigation Equipment, Except Airborne"},
%FederalSupplyClassification{id: 5826, name: "Radio Navigation Equipment, Airborne"},
%FederalSupplyClassification{id: 5830, name: "Intercommunication and Public Address Systems, Except Airborne"},
%FederalSupplyClassification{id: 5831, name: "Intercommunication and Public Address Systems, Airborne"},
%FederalSupplyClassification{id: 5835, name: "Sound Recording and Reproducing Equipment"},
%FederalSupplyClassification{id: 5836, name: "Video Recording and Reproducing Equipment"},
%FederalSupplyClassification{id: 5840, name: "Radar Equipment, Except Airborne"},
%FederalSupplyClassification{id: 5841, name: "Radar Equipment, Airborne"},
%FederalSupplyClassification{id: 5850, name: "Visible and Invisible Light Communication Equipment"},
%FederalSupplyClassification{id: 5855, name: "Night Vision Equipment, Emitted and Reflected Radiation"},
%FederalSupplyClassification{id: 5860, name: "Stimulated Coherent Radiation Devices, Components, and Accessories"},
%FederalSupplyClassification{id: 5865, name: "Electronic Countermeasures, Counter-Countermeasures and Quick Reaction Capability Equipment"},
%FederalSupplyClassification{id: 5895, name: "Miscellaneous Communication Equipment"},
%FederalSupplyClassification{id: 5905, name: "Resistors"},
%FederalSupplyClassification{id: 5910, name: "Capacitors"},
%FederalSupplyClassification{id: 5915, name: "Filters and Networks"},
%FederalSupplyClassification{id: 5920, name: "Fuses, Arrestors, Absorbers, and Protectors"},
%FederalSupplyClassification{id: 5925, name: "Circuit Breakers"},
%FederalSupplyClassification{id: 5930, name: "Switches"},
%FederalSupplyClassification{id: 5935, name: "Connectors, Electrical"},
%FederalSupplyClassification{id: 5940, name: "Lugs, Terminals, and Terminal Strips"},
%FederalSupplyClassification{id: 5945, name: "Relays and Solenoids"},
%FederalSupplyClassification{id: 5950, name: "Coils and Transformers"},
%FederalSupplyClassification{id: 5955, name: "Oscillators and Piezoelectric Crystals"},
%FederalSupplyClassification{id: 5960, name: "Electron Tubes and Associated Hardware"},
%FederalSupplyClassification{id: 5961, name: "Semiconductor Devices and Associated Hardware"},
%FederalSupplyClassification{id: 5962, name: "Microcircuits, Electronic"},
%FederalSupplyClassification{id: 5963, name: "Electronic Modules"},
%FederalSupplyClassification{id: 5965, name: "Headsets, Handsets, Microphones and Speakers"},
%FederalSupplyClassification{id: 5970, name: "Electrical Insulators and Insulating Materials"},
%FederalSupplyClassification{id: 5975, name: "Electrical Hardware and Supplies"},
%FederalSupplyClassification{id: 5977, name: "Electrical Contact Brushes and Electrodes"},
%FederalSupplyClassification{id: 5980, name: "Optoelectronic Devices and Associated Hardware"},
%FederalSupplyClassification{id: 5985, name: "Antennas, Waveguides, and Related Equipment"},
%FederalSupplyClassification{id: 5990, name: "Synchros and Resolvers"},
%FederalSupplyClassification{id: 5995, name: "Cable, Cord, and Wire Assemblies: Communication Equipment"},
%FederalSupplyClassification{id: 5996, name: "Amplifiers"},
%FederalSupplyClassification{id: 5998, name: "Electrical and Electronic assemblies, Boards, Cards, and Associated Hardware"},
%FederalSupplyClassification{id: 5999, name: "Miscellaneous Electrical and Electronic Components"},
%FederalSupplyClassification{id: 6010, name: "Fiber Optic Conductors"},
%FederalSupplyClassification{id: 6015, name: "Fiber Optic Cables"},
%FederalSupplyClassification{id: 6020, name: "Fiber Optic Cable Assemblies and Harnesses"},
%FederalSupplyClassification{id: 6021, name: "Fiber Optic Switches"},
%FederalSupplyClassification{id: 6030, name: "Fiber Optic Devices"},
%FederalSupplyClassification{id: 6032, name: "Fiber Optic Light Sources and Photo Detectors"},
%FederalSupplyClassification{id: 6035, name: "Fiber Optic Light Transfer and Image Transfer Devices"},
%FederalSupplyClassification{id: 6060, name: "Fiber Optic Interconnectors"},
%FederalSupplyClassification{id: 6070, name: "Fiber Optic Accessories and Supplies"},
%FederalSupplyClassification{id: 6080, name: "Fiber Optic Kits and Sets"},
%FederalSupplyClassification{id: 6099, name: "Miscellaneous Fiber Optic Components"},
%FederalSupplyClassification{id: 6105, name: "Motors, Electrical"},
%FederalSupplyClassification{id: 6110, name: "Electrical Control Equipment"},
%FederalSupplyClassification{id: 6115, name: "Generators and Generator Sets, Electrical"},
%FederalSupplyClassification{id: 6116, name: "Fuel Cell Power Units, Components, and Accessories"},
%FederalSupplyClassification{id: 6117, name: "Solar Electric Power Systems"},
%FederalSupplyClassification{id: 6120, name: "Transformers: Distribution and Power Station"},
%FederalSupplyClassification{id: 6125, name: "Converters, Electrical, Rotating"},
%FederalSupplyClassification{id: 6130, name: "Converters, Electrical, Nonrotating"},
%FederalSupplyClassification{id: 6135, name: "Batteries, Nonrechargeable"},
%FederalSupplyClassification{id: 6140, name: "Batteries, Rechargeable"},
%FederalSupplyClassification{id: 6145, name: "Wire and Cable, Electrical"},
%FederalSupplyClassification{id: 6150, name: "Miscellaneous Electric Power and Distribution Equipment"},
%FederalSupplyClassification{id: 6160, name: "Miscellaneous Battery Retaining Fixtures, Liners and Ancillary Items"},
%FederalSupplyClassification{id: 6210, name: "Indoor and Outdoor Electric Lighting Fixtures"},
%FederalSupplyClassification{id: 6220, name: "Electric Vehicular Lights and Fixtures"},
%FederalSupplyClassification{id: 6230, name: "Electric Portable and Hand Lighting Equipment"},
%FederalSupplyClassification{id: 6240, name: "Electric Lamps"},
%FederalSupplyClassification{id: 6250, name: "Ballasts, Lampholders, and Starters"},
%FederalSupplyClassification{id: 6260, name: "Nonelectrical Lighting Fixtures"},
%FederalSupplyClassification{id: 6310, name: "Traffic and Transit Signal Systems"},
%FederalSupplyClassification{id: 6320, name: "Shipboard Alarm and Signal Systems"},
%FederalSupplyClassification{id: 6330, name: "Railroad Signal and Warning Devices"},
%FederalSupplyClassification{id: 6340, name: "Aircraft Alarm and Signal Systems"},
%FederalSupplyClassification{id: 6350, name: "Miscellaneous Alarm, Signal, and Security Detection Systems"},
%FederalSupplyClassification{id: 6505, name: "Drugs and Biologicals"},
%FederalSupplyClassification{id: 6508, name: "Medicated Cosmetics and Toiletries"},
%FederalSupplyClassification{id: 6509, name: "Drugs and Biologicals, Veterinary Use"},
%FederalSupplyClassification{id: 6510, name: "Surgical Dressing Materials"},
%FederalSupplyClassification{id: 6515, name: "Medical and Surgical Instruments, Equipment, and Supplies"},
%FederalSupplyClassification{id: 6520, name: "Dental Instruments, Equipment, and Supplies"},
%FederalSupplyClassification{id: 6525, name: "Imaging Equipment and Supplies: Medical, Dental, Veterinary"},
%FederalSupplyClassification{id: 6530, name: "Hospital Furniture, Equipment, Utensils, and Supplies"},
%FederalSupplyClassification{id: 6532, name: "Hospital and Surgical Clothing and Related Special Purpose Items"},
%FederalSupplyClassification{id: 6540, name: "Ophthalmic Instruments, Equipment, and Supplies"},
%FederalSupplyClassification{id: 6545, name: "Replenishable Field Medical Sets, Kits, and Outfits"},
%FederalSupplyClassification{id: 6605, name: "Navigational Instruments"},
%FederalSupplyClassification{id: 6610, name: "Flight Instruments"},
%FederalSupplyClassification{id: 6615, name: "Automatic Pilot Mechanisms and Airborne Gyro Components"},
%FederalSupplyClassification{id: 6620, name: "Engine Instruments"},
%FederalSupplyClassification{id: 6625, name: "Electrical and Electronic Properties Measuring and Testing Instruments"},
%FederalSupplyClassification{id: 6630, name: "Chemical Analysis Instruments"},
%FederalSupplyClassification{id: 6635, name: "Physical Properties Testing and Inspection"},
%FederalSupplyClassification{id: 6636, name: "Environmental Chambers and Related Equipment"},
%FederalSupplyClassification{id: 6640, name: "Laboratory Equipment and Supplies"},
%FederalSupplyClassification{id: 6645, name: "Time Measuring Instruments"},
%FederalSupplyClassification{id: 6650, name: "Optical Instruments, Test Equipment, Components and Accessories"},
%FederalSupplyClassification{id: 6655, name: "Geophysical Instruments"},
%FederalSupplyClassification{id: 6660, name: "Meteorological Instruments and Apparatus"},
%FederalSupplyClassification{id: 6665, name: "Hazard-Detecting Instruments and Apparatus"},
%FederalSupplyClassification{id: 6670, name: "Scales and Balances"},
%FederalSupplyClassification{id: 6675, name: "Drafting, Surveying, and Mapping Instruments"},
%FederalSupplyClassification{id: 6680, name: "Liquid and Gas Flow, Liquid Level, and Mechanical Motion Measuring Instruments"},
%FederalSupplyClassification{id: 6685, name: "Pressure, Temperature, and Humidity Measuring and Controlling Instruments"},
%FederalSupplyClassification{id: 6695, name: "Combination and Miscellaneous Instruments"},
%FederalSupplyClassification{id: 6750, name: "Photographic Supplies"},
%FederalSupplyClassification{id: 6810, name: "Chemicals"},
%FederalSupplyClassification{id: 6820, name: "Dyes"},
%FederalSupplyClassification{id: 6850, name: "Miscellaneous Chemical Specialties"},
%FederalSupplyClassification{id: 6910, name: "Training Aids"},
%FederalSupplyClassification{id: 6920, name: "Armament Training Devices"},
%FederalSupplyClassification{id: 7010, name: "ADPE System Configuration"},
%FederalSupplyClassification{id: 7020, name: "ADP Central Processing Unit (CPU, Computer), Analog"},
%FederalSupplyClassification{id: 7021, name: "ADP Central Processing Unit (CPU, Computer), Digital"},
%FederalSupplyClassification{id: 7022, name: "ADP Central Processing Unit (CPU, Computer), Hybrid"},
%FederalSupplyClassification{id: 7025, name: "ADP Input/Output and Storage Devices"},
%FederalSupplyClassification{id: 7035, name: "ADP Support Equipment"},
%FederalSupplyClassification{id: 7045, name: "ADP Supplies"},
%FederalSupplyClassification{id: 7240, name: "Household and Commercial Utility Containers"},
%FederalSupplyClassification{id: 7420, name: "Accounting and Calculating Machines"},
%FederalSupplyClassification{id: 7430, name: "Typewriters and Office Type Composing Machines"},
%FederalSupplyClassification{id: 7490, name: "Miscellaneous Office Machines"},
%FederalSupplyClassification{id: 7510, name: "Office Supplies"},
%FederalSupplyClassification{id: 7530, name: "Stationery and Record Forms"},
%FederalSupplyClassification{id: 7540, name: "Standard Forms"},
%FederalSupplyClassification{id: 7930, name: "Cleaning and Polishing Compounds and Preparations"},
%FederalSupplyClassification{id: 8010, name: "Paints, Dopes, Varnishes, and Related Products"},
%FederalSupplyClassification{id: 8030, name: "Preservative and Sealing Compounds"},
%FederalSupplyClassification{id: 8040, name: "Adhesives"},
%FederalSupplyClassification{id: 8105, name: "Bags and Sacks"},
%FederalSupplyClassification{id: 8110, name: "Drums and Cans"},
%FederalSupplyClassification{id: 8115, name: "Boxes, Cartons, and Crates"},
%FederalSupplyClassification{id: 8125, name: "Bottles and Jars"},
%FederalSupplyClassification{id: 8130, name: "Reels and Spools"},
%FederalSupplyClassification{id: 8135, name: "Packaging and Packing Bulk Materials"},
%FederalSupplyClassification{id: 8140, name: "Ammunition and Nuclear Ordnance Boxes, Packages and Special Containers"},
%FederalSupplyClassification{id: 8145, name: "Specialized Shipping and Storage Containers"},
%FederalSupplyClassification{id: 8150, name: "Freight Containers"},
%FederalSupplyClassification{id: 8305, name: "Textile Fabrics"},
%FederalSupplyClassification{id: 9150, name: "Oils and Greases: Cutting, Lubricating, and Hydraulic"},
%FederalSupplyClassification{id: 9160, name: "Miscellaneous Waxes, Oils, and Fats"},
%FederalSupplyClassification{id: 9320, name: "Rubber Fabricated Materials"},
%FederalSupplyClassification{id: 9330, name: "Plastics Fabricated Materials"},
%FederalSupplyClassification{id: 9999, name: "Miscellaneous Items"}
]


Enum.map(fscs, fn fsc -> Repo.insert!(fsc) end)


alias Adellis.Catalog.FederalSupplyGroup
fsgs = [ 
%FederalSupplyGroup{id: 12, name: "Fire Control Equipment"},
%FederalSupplyGroup{id: 15, name: "Aircraft and Airframe Structural Components"},
%FederalSupplyGroup{id: 16, name: "Aircraft Components and Accessories"},
%FederalSupplyGroup{id: 17, name: "Aircraft Launching, Landing, and Ground Handling Equipment"},
%FederalSupplyGroup{id: 18, name: "Space Vehicles"},
%FederalSupplyGroup{id: 19, name: "Ships, Small Craft, Pontoons, and Floating Docks"},
%FederalSupplyGroup{id: 20, name: "Ship and Marine Equipment"},
%FederalSupplyGroup{id: 22, name: "Railway Equipment"},
%FederalSupplyGroup{id: 23, name: "Ground Effects Vehicles, Motor Vehicles, Trailers, and Cycles"},
%FederalSupplyGroup{id: 24, name: "Tractors"},
%FederalSupplyGroup{id: 25, name: "Vehicular Equipment Components"},
%FederalSupplyGroup{id: 26, name: "Tires and Tubes"},
%FederalSupplyGroup{id: 28, name: "Engines, Turbines and Components"},
%FederalSupplyGroup{id: 29, name: "Engine Accessories"},
%FederalSupplyGroup{id: 30, name: "Mechanical Power Transmission Equipment"},
%FederalSupplyGroup{id: 31, name: "Bearings"},
%FederalSupplyGroup{id: 32, name: "Woodworking Machinery and Equipment"},
%FederalSupplyGroup{id: 34, name: "Metalworking Machinery"},
%FederalSupplyGroup{id: 35, name: "Service and Trade Equipment"},
%FederalSupplyGroup{id: 36, name: "Special Industry Machinery"},
%FederalSupplyGroup{id: 37, name: "Agricultural Machinery and Equipment"},
%FederalSupplyGroup{id: 38, name: "Construction, Mining, Excavating, and Highway Maintenance Equipment"},
%FederalSupplyGroup{id: 39, name: "Materials Handling Equipment"},
%FederalSupplyGroup{id: 40, name: "Rope, Cable, Chain, and Fittings"},
%FederalSupplyGroup{id: 41, name: "Refrigeration, Air-Conditioning, and Air Circulating Equipment"},
%FederalSupplyGroup{id: 42, name: "Fire Fighting, Rescue and Safety Equipment"},
%FederalSupplyGroup{id: 43, name: "Pumps and Compressors"},
%FederalSupplyGroup{id: 44, name: "Furnace, Steam Plant, Drying Equipment; and Nuclear Reactors"},
%FederalSupplyGroup{id: 45, name: "Plumbing, Heating, and Sanitation Equipment"},
%FederalSupplyGroup{id: 46, name: "Water Purification and Sewage Treatment Equipment"},
%FederalSupplyGroup{id: 47, name: "Pipe, Tubing, Hose and Fittings"},
%FederalSupplyGroup{id: 48, name: "Valves"},
%FederalSupplyGroup{id: 49, name: "Maintenance and Repair Shop Equipment"},
%FederalSupplyGroup{id: 51, name: "Hand Tools"},
%FederalSupplyGroup{id: 52, name: "Measuring Tools"},
%FederalSupplyGroup{id: 53, name: "Hardware and Abrasives"},
%FederalSupplyGroup{id: 54, name: "Prefabricated Structures and Scaffolding"},
%FederalSupplyGroup{id: 56, name: "Construction and Building Materials"},
%FederalSupplyGroup{id: 58, name: "Communication, Detection and Coherent Radiation Equipment"},
%FederalSupplyGroup{id: 59, name: "Electrical and Electronic Equipment Components"},
%FederalSupplyGroup{id: 60, name: "Fiber Optics Materials, Components, Assemblies, Accessories"},
%FederalSupplyGroup{id: 61, name: "Electric Wire and Power and Distribution Equipment"},
%FederalSupplyGroup{id: 62, name: "Lighting Fixtures and Lamps"},
%FederalSupplyGroup{id: 63, name: "Alarm, Signal and Security Detection Systems"},
%FederalSupplyGroup{id: 65, name: "Medical, Dental, and Veterinary Equipment and Supplies"},
%FederalSupplyGroup{id: 66, name: "Instruments and Laboratory Equipment"},
%FederalSupplyGroup{id: 67, name: "Photographic Equipment"},
%FederalSupplyGroup{id: 68, name: "Chemicals and Chemical Products"},
%FederalSupplyGroup{id: 69, name: "Training Aids and Devices"},
%FederalSupplyGroup{id: 70, name: "General Purpose Automatic Data Processing Equipment (Including Firmware), Software, Supplies and Support Equipment"},
%FederalSupplyGroup{id: 72, name: "Household and Commercial Furnishings and Appliances"},
%FederalSupplyGroup{id: 74, name: "Office Machines, Text Processing Systems, and Visible Record Equipment"},
%FederalSupplyGroup{id: 75, name: "Office Supplies and Devices"},
%FederalSupplyGroup{id: 79, name: "Cleaning Equipment and Supplies"},
%FederalSupplyGroup{id: 80, name: "Brushes, Paints, Sealers and Adhesives"},
%FederalSupplyGroup{id: 81, name: "Containers, Packaging, and Packing Supplies"},
%FederalSupplyGroup{id: 83, name: "Textiles, Leathers, Furs, Apparel and Shoe Findings, Tents and Flags"},
%FederalSupplyGroup{id: 91, name: "Fuels, Lubricants, Oils and Waxes"},
%FederalSupplyGroup{id: 93, name: "Nonmetallic Fabricated Materials"},
%FederalSupplyGroup{id: 99, name: "Miscellaneous"}
]


Enum.map(fsgs, fn fsg -> Repo.insert!(fsg) end)


alias Adellis.Sales.Condition
conditions = [ 
%Condition{code: "FN", description: "FACTORY NEW"},
%Condition{code: "NE", description: "NEW MATERIAL"},
%Condition{code: "NS", description: "NEW SURPLUS"},
%Condition{code: "OH", description: "OVERHAULED"},
%Condition{code: "SV", description: "SERVICEABLE"},
%Condition{code: "RP", description: "REPAIRABLE"},
%Condition{code: "AR", description: "AS REMOVED"}
]


Enum.map(conditions, fn condition -> Repo.insert!(condition) end)


alias Adellis.Sales.Priority
priorities = [ 
%Priority{code: "AOG", description: "AIRCRAFT ON GROUND"},
%Priority{code: "IMMEDIATE", description: "WITHIN 1-2 WEEKS"},
%Priority{code: "FLEXIBLE", description: "NO SPECIFIC TIME"}
]


Enum.map(priorities, fn priority -> Repo.insert!(priority) end)


alias Adellis.Catalog.ShelfLife
shelf_lives = [ 
%ShelfLife{code: "A", life: 1},
%ShelfLife{code: "B", life: 2},
%ShelfLife{code: "C", life: 3},
%ShelfLife{code: "D", life: 4},
%ShelfLife{code: "E", life: 5},
%ShelfLife{code: "F", life: 6},
%ShelfLife{code: "G", life: 9},
%ShelfLife{code: "H", life: 12},
%ShelfLife{code: "J", life: 15},
%ShelfLife{code: "K", life: 18},
%ShelfLife{code: "L", life: 21},
%ShelfLife{code: "M", life: 24},
%ShelfLife{code: "N", life: 27},
%ShelfLife{code: "P", life: 30},
%ShelfLife{code: "Q", life: 36},
%ShelfLife{code: "R", life: 48},
%ShelfLife{code: "S", life: 50},
%ShelfLife{code: "I", life: 72},
%ShelfLife{code: "T", life: 84},
%ShelfLife{code: "U", life: 96},
%ShelfLife{code: "W", life: 120},
%ShelfLife{code: "Y", life: 180},
%ShelfLife{code: "Z", life: 240}
]


Enum.map(shelf_lives, fn shelf_life -> Repo.insert!(shelf_life) end)



