alias Adellis.Catalog.FederalSupplyGroup
fsgs = [ 
%FederalSupplyGroup{id: 12, name: "Fire Control Equipment"},
%FederalSupplyGroup{id: 15, name: "Aircraft and Airframe Structural Components"},
%FederalSupplyGroup{id: 16, name: "Aircraft Components and Accessories"},
%FederalSupplyGroup{id: 17, name: "Aircraft Launching, Landing, and Ground Handling Equipment"},
%FederalSupplyGroup{id: 18, name: "Space Vehicles"},
%FederalSupplyGroup{id: 19, name: "Ships, Small Craft, Pontoons, and Floating Docks"},
%FederalSupplyGroup{id: 20, name: "Ship and Marine Equipment"},
%FederalSupplyGroup{id: 22, name: "Railway Equipment"},
%FederalSupplyGroup{id: 23, name: "Ground Effects Vehicles, Motor Vehicles, Trailers, and Cycles"},
%FederalSupplyGroup{id: 24, name: "Tractors"},
%FederalSupplyGroup{id: 25, name: "Vehicular Equipment Components"},
%FederalSupplyGroup{id: 26, name: "Tires and Tubes"},
%FederalSupplyGroup{id: 28, name: "Engines, Turbines and Components"},
%FederalSupplyGroup{id: 29, name: "Engine Accessories"},
%FederalSupplyGroup{id: 30, name: "Mechanical Power Transmission Equipment"},
%FederalSupplyGroup{id: 31, name: "Bearings"},
%FederalSupplyGroup{id: 32, name: "Woodworking Machinery and Equipment"},
%FederalSupplyGroup{id: 34, name: "Metalworking Machinery"},
%FederalSupplyGroup{id: 35, name: "Service and Trade Equipment"},
%FederalSupplyGroup{id: 36, name: "Special Industry Machinery"},
%FederalSupplyGroup{id: 37, name: "Agricultural Machinery and Equipment"},
%FederalSupplyGroup{id: 38, name: "Construction, Mining, Excavating, and Highway Maintenance Equipment"},
%FederalSupplyGroup{id: 39, name: "Materials Handling Equipment"},
%FederalSupplyGroup{id: 40, name: "Rope, Cable, Chain, and Fittings"},
%FederalSupplyGroup{id: 41, name: "Refrigeration, Air-Conditioning, and Air Circulating Equipment"},
%FederalSupplyGroup{id: 42, name: "Fire Fighting, Rescue and Safety Equipment"},
%FederalSupplyGroup{id: 43, name: "Pumps and Compressors"},
%FederalSupplyGroup{id: 44, name: "Furnace, Steam Plant, Drying Equipment; and Nuclear Reactors"},
%FederalSupplyGroup{id: 45, name: "Plumbing, Heating, and Sanitation Equipment"},
%FederalSupplyGroup{id: 46, name: "Water Purification and Sewage Treatment Equipment"},
%FederalSupplyGroup{id: 47, name: "Pipe, Tubing, Hose and Fittings"},
%FederalSupplyGroup{id: 48, name: "Valves"},
%FederalSupplyGroup{id: 49, name: "Maintenance and Repair Shop Equipment"},
%FederalSupplyGroup{id: 51, name: "Hand Tools"},
%FederalSupplyGroup{id: 52, name: "Measuring Tools"},
%FederalSupplyGroup{id: 53, name: "Hardware and Abrasives"},
%FederalSupplyGroup{id: 54, name: "Prefabricated Structures and Scaffolding"},
%FederalSupplyGroup{id: 56, name: "Construction and Building Materials"},
%FederalSupplyGroup{id: 58, name: "Communication, Detection and Coherent Radiation Equipment"},
%FederalSupplyGroup{id: 59, name: "Electrical and Electronic Equipment Components"},
%FederalSupplyGroup{id: 60, name: "Fiber Optics Materials, Components, Assemblies, Accessories"},
%FederalSupplyGroup{id: 61, name: "Electric Wire and Power and Distribution Equipment"},
%FederalSupplyGroup{id: 62, name: "Lighting Fixtures and Lamps"},
%FederalSupplyGroup{id: 63, name: "Alarm, Signal and Security Detection Systems"},
%FederalSupplyGroup{id: 65, name: "Medical, Dental, and Veterinary Equipment and Supplies"},
%FederalSupplyGroup{id: 66, name: "Instruments and Laboratory Equipment"},
%FederalSupplyGroup{id: 67, name: "Photographic Equipment"},
%FederalSupplyGroup{id: 68, name: "Chemicals and Chemical Products"},
%FederalSupplyGroup{id: 69, name: "Training Aids and Devices"},
%FederalSupplyGroup{id: 70, name: "General Purpose Automatic Data Processing Equipment (Including Firmware), Software, Supplies and Support Equipment"},
%FederalSupplyGroup{id: 72, name: "Household and Commercial Furnishings and Appliances"},
%FederalSupplyGroup{id: 74, name: "Office Machines, Text Processing Systems, and Visible Record Equipment"},
%FederalSupplyGroup{id: 75, name: "Office Supplies and Devices"},
%FederalSupplyGroup{id: 79, name: "Cleaning Equipment and Supplies"},
%FederalSupplyGroup{id: 80, name: "Brushes, Paints, Sealers and Adhesives"},
%FederalSupplyGroup{id: 81, name: "Containers, Packaging, and Packing Supplies"},
%FederalSupplyGroup{id: 83, name: "Textiles, Leathers, Furs, Apparel and Shoe Findings, Tents and Flags"},
%FederalSupplyGroup{id: 91, name: "Fuels, Lubricants, Oils and Waxes"},
%FederalSupplyGroup{id: 93, name: "Nonmetallic Fabricated Materials"},
%FederalSupplyGroup{id: 99, name: "Miscellaneous"}
]


Enum.map(fsgs, fn fsc -> Repo.insert!(fsg) end)